### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by MadhuriHR** [ghost1372/Mzip-Android#4]
Hi. I created a folder and I manually compressed with .tar.gz extension. Now I tried to extract using your library but I end up with crash.

Below is the code :
`File srcFile = new File(Environment.getExternalStorageDirectory() + File.separator + "test/test.tar.gz");
        File destFile = new File(Environment.getExternalStorageDirectory() + File.separator + "test");
        RarArchive rarArchive = new RarArchive();
        rarArchive.extractArchive(srcFile,destFile);`

Crash report 
` Caused by: java.lang.NullPointerException: mainheader is null
                                                                        at ir.mahdi.mzip.rar.Archive.isEncrypted(Archive.java:178)
                                                                        at ir.mahdi.mzip.rar.RarArchive.extractArchive(RarArchive.java:44)`

**Comment by ghost1372** [comment]
Hello
This library was created a year ago for a project That, I needed rar and zip.
This library is a combination of 2 libraries junrar and zip4j
It seems that Unfortunately, the RarArchive class does not support tar format, please test with ZipArchive class mybe it work.

**Comment by ecenllen** [comment]
Hello
Support for rar version 5 is not yet implemented!
how can i do then?
